# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wf1SrW3Df7AKCKoYlhxYn6qlux62KIbB

Task 1
"""

age = int(input('Enter your age:'))
if age >= 18:
  print('You are old enough to drive')
else:
  print('Wait for the missing amount of years')

"""Task 2"""

my_age = int(input('My age:'))
your_age = int(input('Enter your age:'))

if my_age > your_age:
  age_difference = my_age - your_age
  if age_difference==1:
    print(f'I am older than you by {age_difference}','year')
  else:
    print(f'I am older than you by {age_difference}','years')

elif my_age<your_age:
  age_difference = your_age - my_age
  if age_difference==1:
    print(f'I am younger than you by {age_difference}','year')
  else:
    print(f'I am younger than you by {age_difference}','years')
else:
  print('We are of same age')

"""Task 3"""

a = float(input('Enter first number:'))
b = float(input('Enter second number:'))

if a > b:
  print(f'{a} is greater than {b}')
elif a < b:
  print(f'{a} is smaller than {b}')
else:
  print(f'{a} is equal to {b}')

